version: "3"

services:
  app:
    build: .
    restart: always
    volumes:
      - static_volume:/data/static/
      - ./data/media:/data/media/
      - ./data/log:/data/log/
    depends_on:
      - database
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.staging
    env_file:
      - ./.env

  database:
    image: mariadb:10.8
    restart: always
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_db
    env_file:
      - ./.env

  revproxy:
    image: nginx
    restart: always
    depends_on:
      - app
    ports:
      - 8000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/static
      #- ./data/media:/usr/src/app/media

volumes:
  static_volume:
